name: Metrics
on:
  schedule: [{cron: "* 12 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, community, repositories, metadata
          clean_workflows: failure, startup_failure, cancelled
          committer_message: "Update metrics."
          committer_token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/New_York
          delay: 1
          filename: metrics.svg
          output_action: commit
          output_condition: data-changed
          plugin_achievements: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_charts: no
          plugin_habits_facts: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: rainbow
          plugin_languages_ignored: less, dockerfile
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_starred: 1
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          user: movrsi
